# registration
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientName: Naver
            clientId: K1JRC5Hja52bvwGuHHt5
            clientSecret: jGx4WYWXgT
            redirect_uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            scope:
              - name
              - nickname
              - email
          kakao:
            client-name: Kakao
            client-id: ce30ee24f7e16c695ebacaa21ee663ec
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST

      # provider 설정
        provider:
         naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
         kakao:
          authorization_uri: https://kauth.kakao.com/oauth/authorize
          token_uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user_name_attribute: id
